version: "3.3"

services:
  server:
    build: https://github.com/Llirik1337/orders-backend.git#develop
    environment:
      - DATABASE_URL=mongodb://mongo:27017/bstu-orders
      - SERVER_PORT=3000
    ports:
    - 3000:3000
    volumes:
    - ~/.ssh:/root/.ssh
    links:
        - mongo
    depends_on:
        - mongo
  mongo:
      image: mongo:latest
      environment:
        - MONGO_DATA_DIR=/data/db
        # - MONGO_LOG_DIR=/dev/null
      volumes:
        - ./data/db:/data/db
      ports:
          - 27017:27017
      command: mongod # --quiet
  client:
    build: 
      context: https://gitlab.com/altyn.stanislav/bstuorders.git#master
      args:
        - AUTH_URL=http://localhost:3000
        - STORE_URL=http://localhost:3000/graphql
    ports:
      - 80:80
    volumes:
      - ~/.ssh:/root/.ssh
    # network_mode: "host"
    depends_on:
      - server
